server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase
    username: postgres
    password: 666
    platform: org.hibernate.dialect.PostgreSQL9Dialect
  jpa:
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        ddl-auto: none
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog.xml
